// Emits SQL that creates (or password-resets) a login user, grants them
// membership of the seed mailbox, and gives them a send-as identity for every
// address in that mailbox (so sending works from day one). Run via
// `make user-local EMAIL=... PASSWORD=...` or `make user-remote ...`, which pipe
// the output through `wrangler d1 execute`.
//
//   npx tsx scripts/create-user.ts <email> <password> [display-name] [mailbox-id]
//
// Hashing happens here, in Node, with the same hashPassword the API verifies
// with — argon2id at production parameters, PHC string format.

import { randomUUID } from "node:crypto";
import { hashPassword } from "../packages/shared/src/password";

const [email, password, displayName = "", mailboxId = "seed-mailbox"] =
  process.argv.slice(2);

if (!email || !password) {
  console.error(
    "usage: npx tsx scripts/create-user.ts <email> <password> [display-name] [mailbox-id]",
  );
  process.exit(1);
}
if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
  console.error(`Not an email address: ${email}`);
  process.exit(1);
}
if (password.length < 8) {
  console.error("Password must be at least 8 characters.");
  process.exit(1);
}

const escape = (s: string) => s.replaceAll("'", "''");
const hash = hashPassword(password);

console.log(`-- Generated by scripts/create-user.ts; do not commit.
-- Re-running with the same email updates the password.
INSERT INTO users (id, email_login, password_hash, display_name, is_admin)
VALUES ('${randomUUID()}', lower('${escape(email)}'), '${hash}', '${escape(displayName)}', 1)
ON CONFLICT(email_login) DO UPDATE SET password_hash = excluded.password_hash;

INSERT OR IGNORE INTO mailbox_members (mailbox_id, user_id, role)
SELECT '${escape(mailboxId)}', id, 'owner' FROM users
WHERE email_login = lower('${escape(email)}');

-- A send-as identity per address in the mailbox; (user_id, address_id) is
-- unique, so OR IGNORE keeps re-runs idempotent.
INSERT OR IGNORE INTO identities (id, user_id, address_id, display_name)
SELECT lower(hex(randomblob(16))), u.id, a.id, '${escape(displayName)}'
FROM users u
JOIN addresses a ON a.mailbox_id = '${escape(mailboxId)}'
WHERE u.email_login = lower('${escape(email)}');
`);
